### PR TITLE
Update Vite to v3 (stalled by WMF CI node version)

### PR DESCRIPTION
**Pull request by micgro42**
This is mainly here to test if GitHub CI works as expected due to the troubles with it in #331

### CODE REVIEW

**Comment by lucaswerkmeister** [comment]
I don’t think we can use Vite 3 yet – Wikimedia CI still uses Node 14.17.5 ([random recent Node build](https://integration.wikimedia.org/ci/job/mwgate-node14-docker/86567/console)), and Vite 3 requires 14.18 or later.

**Comment by micgro42** [comment]
> I don’t think we can use Vite 3 yet – Wikimedia CI still uses Node 14.17.5 ([random recent Node build](https://integration.wikimedia.org/ci/job/mwgate-node14-docker/86567/console)), and Vite 3 requires 14.18 or later.

Ah, and we build it in CI to verify that it is indeed built correctly, right? Meh. Then I'll change this to draft until the WMDE infrastructure updates.

And I'll make a PR for the README, so that it actually says to ignore Vite 3.

**Comment by lucaswerkmeister** [comment]
> Ah, and we build it in CI to verify that it is indeed built correctly, right? Meh.

Yeah, exactly.

> Then I'll change this to draft until the WMDE infrastructure updates.

(Which is T314470.)

> And I'll make a PR for the README, so that it actually says to ignore Vite 3.

Sounds good, thanks – apparently I totally forgot to include this in #308.

**Comment by micgro42** [comment]
This will have to wait until WMF CI updates. README has been updated in #333

**Comment by 40N30E722296800Z** [comment]
Vite is upgraded to version 3 now.

**Comment by lucaswerkmeister** [comment]
(Done in #445.)

**Pull request closed without merging**
