### PR TITLE
Remove emits validators

### PR DESCRIPTION
**Pull request by lucaswerkmeister**
These seem like useless complication to me. The `SpellingVariantInput` validator was even incorrect, I would argue – it would reject `null` as an invalid value, when in fact that’s the correct value when the user hasn’t selected anything or cleared the input.

----

Noticed while working on https://github.com/wmde/new-lexeme-special-page/pull/223.

### CODE REVIEW

**Comment by lucaswerkmeister** [comment]
> Though I would note that these validators (same as prop validators, prop types, etc.) are only a development aid. They are not present in the actual production build.

Honestly, I didn’t find it helpful during development ^^ in #223, we didn’t remember how to specify an `emits` event name without a validator when other events already have a validator, so we ended up writing a pointless `returns true` validator (later removed in d1a625dedfff106e4eb22df204f75c790e64b411). But I uploaded #227 as an alternative.

**Comment by micgro42** [comment]
> > Though I would note that these validators (same as prop validators, prop types, etc.) are only a development aid. They are not present in the actual production build.
> 
> Honestly, I didn’t find it helpful during development ^^ in #223, we didn’t remember how to specify an `emits` event name without a validator when other events already have a validator, so we ended up writing a pointless `returns true` validator (later removed in [d1a625d](https://github.com/wmde/new-lexeme-special-page/commit/d1a625dedfff106e4eb22df204f75c790e64b411)). But I uploaded #227 as an alternative.

I think, I would like to avoid going back to just a plain listing of events. What I could see as a workable way forward could be to use only [types for events](https://vuejs.org/guide/typescript/composition-api.html#typing-component-emits) by default and include a validator only when the emitted payload is particularly complex. What do you think?

**Comment by lucaswerkmeister** [comment]
> I think, I would like to avoid going back to just a plain listing of events. What I could see as a workable way forward could be to use only [types for events](https://vuejs.org/guide/typescript/composition-api.html#typing-component-emits) by default and include a validator only when the emitted payload is particularly complex. What do you think?

Oh nice, I didn’t know about types for events. If it can be combined with a validator function, that sounds great to me.

In the meantime, I think we can merge #227 and close this?

**Comment by micgro42** [comment]
> > I think, I would like to avoid going back to just a plain listing of events. What I could see as a workable way forward could be to use only [types for events](https://vuejs.org/guide/typescript/composition-api.html#typing-component-emits) by default and include a validator only when the emitted payload is particularly complex. What do you think?
> 
> Oh nice, I didn’t know about types for events. If it can be combined with a validator function when necessary, that sounds great to me.
> 
> In the meantime, I think we can merge #227 and close this?

I approved #227, but I'm not sure that they can be combined. The linked docs state:

> using either runtime declaration OR type declaration:

(emphasis in the original). I would interpret this as meaning XOR.

**Comment by lucaswerkmeister** [comment]
I was hoping that exclusivity was only between the list/array syntax and the type syntax, but that the type syntax could still be combined with the object syntax… I’ll try it out, I guess ^^

**Comment by lucaswerkmeister** [comment]
Dangit, doesn’t work.

```typescript
export declare function defineEmits<EE extends string = string>(emitOptions: EE[]): EmitFn<EE[]>;

export declare function defineEmits<E extends EmitsOptions = EmitsOptions>(emitOptions: E): EmitFn<E>;

export declare function defineEmits<TypeEmit>(): TypeEmit;
```

Oh well. Then I guess we either use `EmitsOptions` if we want any validation functions, or `TypeEmit` if we’re okay with types only, but never `EE[]`?

**Pull request closed without merging**
