### PR TITLE
Use tabs to indent yaml and json files

### PR DESCRIPTION
**Pull request by micgro42**
This is basically a follow-up to #4. Some form of linting for this will be added in the next PR.

### CODE REVIEW

**Comment by lucaswerkmeister** [comment]
The dependabot YAML still seems to be indented with spaces as far as I can tell?

(Though for such a heavily-nested format, I’d also be fine with spaces, to be honest.)

**Comment by micgro42** [comment]
> The dependabot YAML still seems to be indented with spaces as far as I can tell?
> 
> (Though for such a heavily-nested format, I’d also be fine with spaces, to be honest.)

Oh, you're right. Apparently, yaml cannot be indented with tabs: http://yaml.org/faq.html :thinking:

**Comment by lucaswerkmeister** [comment]
Ah, that’s good to know :D

**Comment by micgro42** [comment]
Ok, now `.yaml` should be consistently updated with **four** spaces and other files with tabs.

**Review by lucaswerkmeister — DISMISSED** [review]
(Commit message is arguably outdated now, though.)

**Review by lucaswerkmeister — APPROVED** [review]

**Comment by micgro42** [comment]
Fixed the commit message. Though I think, I maybe should undo that "Dismiss stale pull request approvals when new commits are pushed" option :thinking:

**Pull request merged**
