### PR TITLE
Fix Vue version

### PR DESCRIPTION
**Pull request by lucaswerkmeister**
See individual commit messages. (Reverts #774.)

### CODE REVIEW

**Review by yerdua — APPROVED** [review]

**Comment by lucaswerkmeister** [comment]
Updated after conflicts (I ended up just recreating the first commit from scratch).

**Comment by lucaswerkmeister** [comment]
Wondering if we should also pin the versions in `package.json` as `3.4.27` rather than `^3.4.27`…

**Comment by yerdua** [comment]
> Wondering if we should also pin the versions in `package.json` as `3.4.27` rather than `^3.4.27`…

Makes sense to me. Is there any harm in doing so?

**Comment by lucaswerkmeister** [comment]
Don’t think so, I just didn’t think of it yesterday and then thought of it today while idly staring at the terminal output from yesterday ^^ I’ll update the PR.

**Comment by lucaswerkmeister** [comment]
Ended up putting it in a separate commit because I didn’t think it really fit into either of the existing ones.

**Review by yerdua — APPROVED** [review]

**Pull request merged**
